apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: offer-management

resources:
  - namespace.yaml
  - ingress.yaml
  - ../../base

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: offer-management
    behavior: merge
    literals:
      - kafka-bootstrap-servers=offer-management-kafka:9092
      - spring-profile-active=dev
      - JWT_ISSUER_URI=http://offer-management-keycloak:8080/realms/iot

secretGenerator:
  - name: offer-management-db
    literals:
      - jdbc-url=jdbc:postgresql://offer-management-db-postgresql:5432/offer-management
      - username=offer-management
      - password=offer-management
